<div>
  <small class="copyright">
    <div class="footer_link">
      <a class="footer_link3" href="#"><a href="#"><?= $block->escapeHtml(__('Privacy Policy')) ?></a>
        <a class="footer_link1" href="#"><a href="#"><?= $block->escapeHtml(__('TERMS & CONDITION')) ?></a>
          <a class="footer_link2" href="#"><a href="#"><?= $block->escapeHtml(__('SITE MAP')) ?></a>
    </div>
    <span> <?php /* @escapeNotVerified */ echo $block->getCopyright() ?>
    </span>
  </small>
</div>
<div class="banner">

  <div class="cand">
    <div class="divHead"><i class="fab fa-envira"></i></div>
    <div class="divCell" id="can"><?= $block->escapeHtml(__('100% CANADIAN DESIGNS')) ?></div>
  </div>
  <div class="estb">
    <div class="divHead"><i class="fas fa-shield-alt"></i></div>
    <div class="divCell" id="est"><?= $block->escapeHtml(__('ESTABLISHED SINCE 1994')) ?></div>
  </div>
  <div class="gen">
    <div class="divHead"><i class="far fa-file"></i></div>
    <div class="divCell" id="soc"><?= $block->escapeHtml(__('GENIUNE LEATHER GOOD')) ?></div>
  </div>
</div>

<div class="banner1">
  <div id="ban"><?= $block->escapeHtml(__('UPTO 30% OFF SPRING SHOES')) ?></div>

  <div class="banner2">
    <div id="ban2"><?= $block->escapeHtml(__('BECAUSE SHE ROCKS')) ?></div>
    <div id="ban3"><?= $block->escapeHtml(__('CELEBRATE HER MAY 8.')) ?></div>
    <div id="ban4"><?= $block->escapeHtml(__('LOREM IPSUM')) ?></div>
  </div>
</div>

<style>
  .banner1 {
    position: absolute;
    width: 100%;
    left: 0%;
    top: 1200px;
  }

  .banner2 {

    margin-left: 60%;
    margin-bottom: 25px;
    position: absolute;
    left: 0%;
    text-align: center;
    top: 1%;
  }

  #ban {
    font-weight: bold;
    color: white;
    font-size: 21px;
    font-family: "Lucida Console", Monaco, monospace;
    font-weight: bold;
    position: absolute;
    left: 18%;
  }

  #ban2 {
    font-weight: bold;
    font-size: 21px;

    color: white;

    font-family: "Lucida Console", Monaco, monospace;
  }

  #ban3 {
    color: white;
    font-size: 15px;
    font-family: "Lucida Console", Monaco, monospace;
    color: pink;
  }

  #ban4 {
    color: white;
    font-size: 15px;
    font-family: "Lucida Console", Monaco, monospace;
    color: pink;
  }
</style>