<div>
    <small class="copyright">
        <div class="footer_link">
            <a class="footer_link3" href="#"><a href="#"><?= $block->escapeHtml(__('Privacy Policy')) ?></a>
                <a class="footer_link1" href="#"><a href="#"><?= $block->escapeHtml(__('TERMS & CONDITION')) ?></a>
                    <a class="footer_link2" href="#"><a href="#"><?= $block->escapeHtml(__('SITE MAP')) ?></a>
        </div>
        <span> <?php /* @escapeNotVerified */ echo $block->getCopyright() ?>
        </span>
    </small>
</div>