<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="block newsletter">
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <span class="label">
                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?= $block->escapeHtmlAttr(__('')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </label>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary"
                        title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                    <span><?= $block->escapeHtml(__('GO')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>


<div class="divTable unstyledTable">
    <div class="divTableBody">
        <div class="divTableRow">
            <div class="divTableCell">    <img src="<?php echo $this->getViewFileUrl('images/divider.png'); ?>" id="divider">
            </div><div class="divTableCell">    <img src="<?php echo $this->getViewFileUrl('images/newww.jpg'); ?>" id="shop"></div><div class="divTableCell">    <img src="<?php echo $this->getViewFileUrl('images/divider.png'); ?>" id="divider1"></div><div class="divTableCell"><div class="soc"> <div class="follow">
    <?= $block->escapeHtml(__('Follow us')) ?>
        </div>
        <img src="<?php echo $this->getViewFileUrl('images/fac.jpg'); ?>" id="icon">
        <img src="<?php echo $this->getViewFileUrl('images/twt.jpg'); ?>" id="icon">
        <img src="<?php echo $this->getViewFileUrl('images/lin.jpg'); ?>" id="icon">
        <img src="<?php echo $this->getViewFileUrl('images/soc.jpg'); ?>" id="icon"></div>
        </div>
    </div>
</div>
