<div class="divTable footerMenu">
    <div class="divTableHeading">
        <div class="divTableRow">
            <div class="divTableHead"><?= $block->escapeHtml(__('CUSTOMER SERVICE')) ?></div>
            <div class="divTableHead"><?= $block->escapeHtml(__('RUDSOK')) ?></div>
            <div class="divTableHead"><?= $block->escapeHtml(__('CONNECT WITH US')) ?></div>
        </div>
        <br>
    </div>
    <div class="divTableBody">
        <div class="divTableRow">
            <div class="divTableCell"><a href="#"><?= $block->escapeHtml(__('FAQ')) ?></a></div>
            <div class="divTableCell"><a href="#"><?= $block->escapeHtml(__('ABOUT US')) ?></a></div>
            <div class="divTableCell" id="social"><a href="#" class="fab fa-facebook-f"></a><a href="#" class="fab fa-tumblr"></a><a href="#" class="fab fa-pinterest-p"></a><a href="#" class="fab fa-instagram"></a><a href="#" class="fab fa-youtube"></a></div>
        </div>
        <div class="divTableRow">
            <div class="divTableCell"><a href="#"><?= $block->escapeHtml(__('ORDER STATUS')) ?></a></div>
            <div class="divTableCell"><a href="#"><?= $block->escapeHtml(__('STORE LOCATOR')) ?></a></div>
            <div class="divTableCell"></div>
        </div>
        <div class="divTableRow">
            <div class="divTableCell"><a href="#"><?= $block->escapeHtml(__('SHIPPING INFORMATION')) ?></a></div>
            <div class="divTableCell"><a href="#"><?= $block->escapeHtml(__('GIFT CARD')) ?></a></div>
            <div class="divTableCell"></div>
        </div>
        <div class="divTableRow">
            <div class="divTableCell"><a href="#"><?= $block->escapeHtml(__('RETURN & EXCHANGE')) ?></a></div>
            <div class="divTableCell"><a href="#"><?= $block->escapeHtml(__('CAREER')) ?></a></div>
            <div class="divTableCell"></div>
        </div>
        <div class="divTableRow">
            <div class="divTableCell"><a href="#"><?= $block->escapeHtml(__('SIZE CHART')) ?></a></div>
            <div class="divTableCell"><a href="#"><?= $block->escapeHtml(__('WHOLESALES')) ?></a></div>
            <div class="divTableCell"></div>
        </div>
        <div class="divTableRow">
            <div class="divTableCell"><a href="#"><?= $block->escapeHtml(__('CONTACT US')) ?></a></div>
            <div class="divTableCell"><a href="#"><?= $block->escapeHtml(__('PRESS INQUIRIES')) ?></a></div>
            <div class="divTableCell"></div>
        </div>
        <div class="divTableRow">
            <div class="divTableCell"></div>
            <div class="divTableCell"><a href="#"><?= $block->escapeHtml(__('COPORATE GIFTING')) ?></a></div>
            <div class="divTableCell"></div>
        </div>
    </div>
</div>
<i id="globe" class="fas fa-globe"></i>
<i class="fab fa-canadian-maple-leaf"></i>