<table id="footer_tbl">
    <tr>
        <th><?= $block->escapeHtml(__('CUSTOMER SERVICE')) ?></th>
        <th><?= $block->escapeHtml(__('RUDSOK')) ?></th>
        <th><?= $block->escapeHtml(__('CONNECT WITH US')) ?></th>
    </tr>
    <tr>
        <td><?= $block->escapeHtml(__('FAQ')) ?></td>
        <td><?= $block->escapeHtml(__('ABOUT US')) ?></td>
        <td id="social"><a href="#" class="fab fa-facebook-f"></a><a href="#" class="fab fa-tumblr"></a><a href="#" class="fab fa-pinterest-p"></a><a href="#" class="fab fa-instagram"></a><a href="#" class="fab fa-youtube"></a></td>
    </tr>
    <tr>
        <td><?= $block->escapeHtml(__('ORDER STATUS')) ?></td>
        <td><?= $block->escapeHtml(__('STORE LOCATOR')) ?></td>
    </tr>
    <tr>
        <td><?= $block->escapeHtml(__('SHIPPING INFORMATION')) ?></td>
        <td><?= $block->escapeHtml(__('GIFT CARDS')) ?></td>
    </tr>
    <tr>
        <td><?= $block->escapeHtml(__('RETURN & EXCHANGE')) ?></td>
        <td><?= $block->escapeHtml(__('CAREER')) ?></td>
    </tr>
    <tr>
        <td><?= $block->escapeHtml(__('SIZE CHART')) ?></td>
        <td><?= $block->escapeHtml(__('WHOLESALES')) ?></td>
    </tr>
    <tr>
        <td><?= $block->escapeHtml(__('CONTACT US')) ?></td>
        <td><?= $block->escapeHtml(__('PRESS INQUIRIES')) ?></td>
    </tr>
    <tr>
        <td></td>
        <td><?= $block->escapeHtml(__('COPORATE GIFTING')) ?></td>
    </tr>
</table>