<table>
    <tr>
        <th>CUSTOMER SERVICE</th>
        <th>RUDSOK</th>
    </tr>
    <tr>
        <td>FAQ</td>
        <td>ABOUT US</td>
    </tr>
    <tr>
        <td>ORDER STATUS</td>
        <td>STORE LOCATOR</td>
    </tr>
    <tr>
        <td>SHIPPING INFORMATION</td>
        <td>GIFT CARDS</td>
    </tr>
    <tr>
        <td>RETURN & EXCHANGE</td>
        <td>CAREER</td>
    </tr>
    <tr>
        <td>SIZE CHART</td>
        <td>WHOLESALES</td>
    </tr>
    <tr>
        <td>CONTACT US</td>
        <td>PRESS INQUIRIES</td>
    </tr>
</table>